before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake test_app"
  - "[ $DB == 'mysql' ] && mysql -e 'create database spree_test;'"
  - "[ $DB == 'postgres' ] && psql -c 'create database spree_test;' -U postgres"
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres
script: "DISPLAY=:99.0 bundle exec rake"
notifications:
  email:
    - ryan@spreecommerce.com
  irc: "irc.freenode.org#spree"
branches:
  only:
    - 1-0-stable
    - master
rvm:
  - 1.8.7
  - 1.9.3
  - ree
